### ISSUE TITLE
Wheel Emulator pinout

### ISSUE THREAD

**Issue by Safandula86** [darknao/btClubSportWheel#13]
Hi, i don't see any information about wheel emulator pinout, can You explain how i must connect teensy 3,2 to Fanatec QR ?

**Comment by lshachar** [comment]
Connect miso, mosi, cs (cable select / slave select), clk, gnd. All these connections have same names on both sides, (i.e, you don't need to connect one side's mosi to other side's miso) 
You might want to feed the teensy with voltage from the steering wheel connector; (once you're done and the emulation is working, you would want the teensy to work without an extra USB cable) you have either 3.3v or 5v to feed the teensy (on the steering wheel connector) , but I didn't get to use a teensy so you should read about the best practices to do that.

https://www.pjrc.com/teensy/external_power.html

**Comment by Safandula86** [comment]
Thank you for help, please correct me if I'm wrong:
Fanatec QR             Teensy 3.2
1.MISO-------------------12
2.MOSI-------------------11
8.CS----------------------10
6.CLK/SCK----------------13

**Comment by lshachar** [comment]
I believe you need to switch MISO and MOSI:
1.MISO-------------------11
2.MOSI-------------------12
8.CS----------------------10
6.CLK/SCK----------------13

from the code:
`
  CORE_PIN13_CONFIG = PORT_PCR_MUX(2);
  CORE_PIN11_CONFIG = PORT_PCR_DSE | PORT_PCR_MUX(2);
  CORE_PIN12_CONFIG = PORT_PCR_MUX(2);
  CORE_PIN10_CONFIG = PORT_PCR_MUX(2);
`

Pins 10,12,13 - are defined as inputs
Pin 11 - is defined as output (Slave Output, i.e. SO.  i.e. MI-SO)

**Comment by Safandula86** [comment]
Thank You very much.
